LawCommunity/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import HomeView, upload_image
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('posts/',include('Posts.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('realEstate/', include('realEstate.urls')),
    path('calculation/', include('calculation.urls')),
    path('salary/', include('salary.urls'))
]

Posts/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path
from .views import ListPostView, DetailPostView, CreatePostView,CommentDeleteView,PostDeleteView,PostUpdateView
from LawCommunity.views import upload_image

app_name = 'Posts'
urlpatterns = [
    path('', ListPostView.as_view(), name='post_list'),
    path('<int:pk>/', DetailPostView.as_view(), name='post_detail'),
    path('new/', CreatePostView.as_view(), name='post_new'),
    path('new/upload_image', upload_image, name="upload_image"),
    path('<int:pk>/', DetailPostView.as_view(), name='detail_post'),
    # 게시물 삭제
    path('<int:pk>/delete/', PostDeleteView.as_view(), name='delete_post'),
    # 댓글 삭제
    path('comment/<int:pk>/delete/', CommentDeleteView.as_view(), name='delete_comment'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post_update'),
]

calculation/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path
from .views import calculate_salary
app_name = 'calculation'
urlpatterns = [
    path('', calculate_salary, name='calculate_salary'),
]

templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>

{% load static %}
{% load humanize %}
<html>
<head>
    <title>{% block title %}My Website{% endblock %}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    {{ block.super }}
    {{ form.media }}
    <style>
      a {
          text-decoration: none;
          color: black;
        }
        .navbar-custom {
            background-color: #FF0000;
            color:white;
        }
        .navbar-custom h1,
        .navbar-custom h2,
        .navbar-custom h3,
        .navbar-custom h4,
        .navbar-custom h5,
        .navbar-custom h6,
        .navbar-custom a,
        .navbar-custom p {
          color: white;
        }
        @font-face {
          font-family: 'SBTitle';
          src: url( {% static 'SB_Window_Font/SBTitle_Bold.ttf' %});
          font-weight: normal;
          font-style: normal;
        }
        @font-face {
          font-family: 'NanumGothic';
          src: url({% static '/static/NanumGothic.ttf' %});
          font-weight: normal;
          font-style: normal;
        }
        @font-face {
          font-family: 'SBTitle_M';
          src: url({% static 'SB_Window_Font/SBTitle_M.ttf' %});
          font-weight: normal;
          font-style: normal;
        }
        .navbar-brand{
        
            font-family : 'SBTitle';
            font-size: 300%
          
        }
        .nav-link{
          font-family : 'SBTitle_M'
        }
        .no-link-style {
          color: inherit;
          text-decoration: none;
        }
p {
  font-family : "NanumGothic";
  font-size:15px;
 }


    </style>
    {% block style %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg bg-danger navbar-custom">
<a class="navbar-brand no-link-style", style="font-face: 'SBTitle'; text-decoration:none;" href="{% url 'home' %}">경사모</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
<span class="navbar-toggler-icon"></span>
</button>

  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
     
      <li class="nav-item">
        <a class="nav-link" href="{% url 'Posts:post_list' %}">자유게시판</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'calculation:calculate_salary' %}">수당 계산기</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">찌라시 게시판</a>
      </li>
    </ul>
  </div>
 
</nav>
<div class="container mx-auto">
    <div class="row">
        <div class="col-md-12">
            {% block content %}{% endblock %}
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
{% block script %}{% endblock %}

</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}

{% block content %}
  <div class="container my-4 mx-auto">
    <hr>
    <div class="d-flex flex-wrap">
      {% for post in posts %}
        <div class="card mb-4 mx-2" style="width: 18rem;">
          <a href="{% url 'Posts:post_detail' pk=post.pk %}" style="text-decoration: none; color: inherit;">
            <div class="card-body">
              <h5 class="card-title">{{ post.title }}</h5>
              <p class="card-text">{{ post.content|striptags|safe }}</p>
            </div>
            <div class="card-footer">
              <small class="text-muted">{{ post.pub_date }}</small>
            </div>
          </a>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}