LawCommunity/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import HomeView, upload_image
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('posts/',include('Posts.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('realEstate/', include('realEstate.urls')),
    path('calculation/', include('calculation.urls')),
    path('salary/', include('salary.urls'))
]

Posts/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path
from .views import ListPostView, DetailPostView, CreatePostView,CommentDeleteView,PostDeleteView,PostUpdateView
from LawCommunity.views import upload_image

app_name = 'Posts'
urlpatterns = [
    path('', ListPostView.as_view(), name='post_list'),
    path('<int:pk>/', DetailPostView.as_view(), name='post_detail'),
    path('new/', CreatePostView.as_view(), name='post_new'),
    path('new/upload_image', upload_image, name="upload_image"),
    path('<int:pk>/', DetailPostView.as_view(), name='detail_post'),
    # 게시물 삭제
    path('<int:pk>/delete/', PostDeleteView.as_view(), name='delete_post'),
    # 댓글 삭제
    path('comment/<int:pk>/delete/', CommentDeleteView.as_view(), name='delete_comment'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post_update'),
]

Posts/models.py
from django.db import models
from django.utils import timezone
from tinymce.models import HTMLField 
from django.urls import reverse

class Post(models.Model):
    title = models.CharField(max_length=20)
    content = HTMLField()
    image = models.ImageField(upload_to='images/', blank=True, null=True)
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=8)
    author_ip = models.CharField(max_length=15)
    password = models.CharField(max_length=100)
    is_deleted = models.BooleanField(default=False)
    def delete_with_password(self, password):
        if self.password == password:
            self.is_deleted= True
            return True
        return False

    def __str__(self):
        return self.title

    def summary(self):
        return self.content[:100]
    
    def get_absolute_url(self):
        return reverse('Posts:post_detail', kwargs={'pk': self.pk})

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.CharField(max_length=8)
    author_ip = models.CharField(max_length=15)
    content = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    password = models.CharField(max_length=100, null=True, blank=True)
    is_deleted = models.BooleanField(default=False) 
    def delete_with_password(self, password):
        if self.password == password:
            self.is_deleted=True
            return True
        return False
    def __str__(self):
        return self.content
    def get_absolute_url(self):
        return reverse('comment_delete', kwargs={'pk': self.pk})

Posts/forms.py
from django import forms
from .models import Post
from .models import Comment
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column

from tinymce.widgets import TinyMCE
class PostForm(forms.ModelForm):
    content = forms.CharField(widget=TinyMCE(attrs={'cols': 80, 'rows': 30}))
    password = forms.CharField(max_length=12, widget=forms.PasswordInput(render_value=False))

    class Meta:
        model = Post
        fields = ['title', 'content', 'author', 'password', 'author_ip']

class CommentForm(forms.ModelForm):
    content = forms.CharField(label='댓글', widget=forms.Textarea(attrs={'rows': 3}))

    class Meta:
        model = Comment
        fields = ['author', 'content', 'password']

Posts/views.py
from django.core.paginator import Paginator
# Create your views here.
from django.views import View
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView,CreateView,DeleteView,UpdateView
from .models import Post, Comment
from .forms import PostForm,CommentForm
from django.views.generic.edit import FormMixin
import datetime
from django.utils import timezone
from datetime import timedelta
from django.http import Http404
from .forms import PostForm
def time_elapsed_string(dt):
    """
    현재 시간과 비교하여 지난 시간을 분으로 환산하여 분 단위로 표시해주는 함수
    :param dt: datetime 객체 (UTC time)
    :return: str, '~분전' 형식의 문자열
    """
    diff = datetime.datetime.utcnow() - dt
    diff_in_minutes = diff.total_seconds() / 60.0

    if diff_in_minutes < 1:
        return '방금 전'
    elif diff_in_minutes < 60:
        return f'{int(diff_in_minutes)}분 전'
    elif diff_in_minutes < 24 * 60:
        return f'{int(diff_in_minutes // 60)}시간 전'
    else:
        return dt.strftime('%Y년 %m월 %d일 %H:%M:%S')

def delete_post(request, pk):
    try:
        post = Post.objects.get(pk=pk)
    except Post.DoesNotExist:
        raise Http404('해당하는 게시물이 없습니다')
    if request.method == 'POST':
        password = request.POST['password']
        if post.delete_with_password(password):
            messages.success(request, '게시물이 삭제되었습니다.')
            return redirect('Posts:post_list')
        else:
            messages.error(request, '비밀번호가 일치하지 않습니다.')
            return redirect('Posts:post_list', pk=pk)
    else:
        return render(request, 'Posts/delete_post.html', {'post': post})
    
    
def delete_comment(request, pk):
    try:
        comment = Comment.objects.get(pk=pk)
    except Comment.DoesNotExist:
        raise Http404('해당하는 댓글이 없습니다')
    if request.method == 'POST':
        password = request.POST['password']
        post_pk = comment.post.pk
        if comment.delete_with_password(password):
            messages.success(request, '댓글이 삭제되었습니다.')
            comment.is_deleted=True
            return redirect('Posts:post_detail', pk=post_pk)
        else:
            messages.error(request, '비밀번호가 일치하지 않습니다.')
            return redirect('Posts:post_detail', pk=post_pk)
    else:
        raise Http404('잘못된 접근입니다.')


class CreatePostView(CreateView):
    model = Post
    fields = ['title', 'content', 'password', 'author',]
    template_name = 'Posts/create_post.html'
    success_url = reverse_lazy('Posts:post_list')

    def form_valid(self, form):
        form.instance.author_ip = self.request.META.get('HTTP_X_FORWARDED_FOR', self.request.META.get('REMOTE_ADDR'))

        return super().form_valid(form)

class ListPostView(ListView):
    model = Post
    template_name = 'Posts/list_post.html'
    context_object_name = 'posts'
    ordering = ['-pub_date']
    paginate_by = 10
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # 현재 페이지 번호 가져오기
        page = self.request.GET.get('page')
        # 현재 페이지 번호에 해당하는 게시물 목록 가져오기
        paginator = Paginator(context['posts'], self.paginate_by)
        context['posts'] = paginator.get_page(page)
        for post in context['posts']:
            post_time = post.pub_date.replace(tzinfo=None)
            post.time = time_elapsed_string(post_time)
        return context
    
    
class DetailPostView(FormMixin, DetailView):
    model = Post
    template_name = 'Posts/detail_post.html'
    context_object_name = 'post'
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = self.get_object()
    
        context['comment_form'] = CommentForm()
        context['time'] = time_elapsed_string(post.pub_date.replace(tzinfo=None))
        comments = Comment.objects.filter(post=post).order_by('-pub_date')
        comment_list = []
        for comment in comments:
            comment_time = comment.pub_date.replace(tzinfo=None)
            comment.time = time_elapsed_string(comment_time)
            comment.id = comment.pk
            comment_list.append(comment)
            print(comment.id)
        context['comment_list'] = comment_list
        context['post_password'] = post.password
        context['comment_count'] = len(Comment.objects.filter(is_deleted =False).filter(post=post))
        
                
                
        return context  

    def get_success_url(self):
        return reverse_lazy('Posts:post_detail', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        form.instance.author_ip = self.request.META.get('HTTP_X_FORWARDED_FOR', self.request.META.get('REMOTE_ADDR'))
        self.object = self.get_object()
        comment = form.save(commit=False)
        comment.post = self.object
        comment.save()
        messages.success(self.request, '댓글이 성공적으로 작성되었습니다.')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, '댓글 작성에 실패하였습니다.')
        return super().form_invalid(form)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

        
class PostDeleteView(DetailView):
    model = Post
    success_url = reverse_lazy('Posts:post_list')
    template_name = 'Posts/post_confirm_delete.html'

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        password = request.POST.get('password')
        if password == self.object.password:
            self.object.is_deleted = True
            self.object.save()
            return redirect(self.get_success_url())
        else:
            return self.get(self, request, *args, **kwargs)

    def form_invalid(self):
        return super().form_invalid()
    def get_success_url(self):
        return reverse_lazy('Posts:post_list')

from django.http import HttpResponseRedirect


class PostUpdateView(UpdateView):
    model = Post
    fields = ['title', 'content', ]
    template_name_suffix = '_update_form'
    def get_object(self): 
        post = get_object_or_404(Post, pk=self.kwargs['pk']) #4
        return post
    def form_valid(self, form):
        form.instance.author_ip = self.request.META.get('HTTP_X_FORWARDED_FOR', self.request.META.get('REMOTE_ADDR'))

        return super().form_valid(form)
    def get_success_url(self):
        return reverse_lazy('Posts:post_detail', kwargs={'pk': self.object.pk})
class CommentDeleteView(DetailView):
    model = Comment
    template_name = 'Posts/comment_confirm_delete.html'

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        password = request.POST.get('password')

        if password == self.object.password:
            self.object.is_deleted = True
            self.object.save()
            return redirect(self.get_success_url())
        else:
            return self.get(self, request, *args, **kwargs)

    def get_success_url(self):
        return self.request.META.get('HTTP_REFERER') or reverse_lazy('home')

Posts/templates/Posts/detail_post.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block style %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/lightbox.min.css' %}">
<script src="{% static 'js/lightbox.min.js' %}"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
<style>

  .posts-header {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    margin-bottom: 20px;
    margin-top: 20px;
  }

  .posts-header h1 {
    margin: 0;
  }

  .post-item {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 20px;
    border: 1px solid #ccc;
    margin-bottom: 20px;
  }

  .post-item h2 {
    margin: 0;
    font-size: 24px;
  }

  .post-item .date {
    font-size: 16px;
  }  
  .emoji {
    font-size: 20px;
  }

  img {
    padding: 0;
    display: block;
    margin: 0 auto auto 0;
    height: 100%; /* Adjust the height as needed */
    width: 100%;  /* Adjust the width as needed */
    cursor: pointer;
  }
   .comment-card {
  background-color: #f5f5f5;
  margin-bottom: 15px;
}
.comment-card .card-body {
  padding: 10px 15px;
}

.comment-card .card-title {
  font-size: 16px;
  margin-bottom: 5px;
}

.comment-card .card-title small {
  font-size: 14px;
}

.comment-card .card-text {
  font-size: 14px;
  margin-bottom: 0;
}

.comment-card .card-footer {
  background-color: #f5f5f5;
  border-top: none;
  font-size: 12px;
  padding: 5px 15px;
}

.comment-card .card-footer small {
  float: right;
  text-align: right;
}



</style>
{% endblock %}
{% block content %}

<div class="container my-5">

    <div class="posts-header">
      <h3 style="font-family: 'NanumGothic'">자유게시판</h1>
      <div>
        <a href="{% url 'Posts:post_new' %}" class="btn">✏️</a>
      </div>
    </div>
    <hr style="height:2px;border-width:0;color:gray;background-color:gray">
  
  <div class="row">
    
    <div class="col-md-12">
      <h2 class="mb-3">{{ post.title }}</h2>
      <div class="d-flex justify-content-between align-items-center mb-4" style="border:3px; background-color: #f5c2c2; padding: 10px; border-radius: 5px;">
        <small class="text-muted" style="margin-right: 10px;"><span class="emoji" style="font-size: 15px;">👤</span> {{ post.author }} ({{ post.author_ip }})</small>
        <div class="d-flex flex-wrap align-items-center">
          <small class="text-muted mr-3"><span class="emoji" style="font-size: 15px;">🕒</span> {{ time }}</small>
          <div class="dropdown">
            <a class="" href="#" role="button" id="postMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-ellipsis-v"></i>
            </a>

            <div class="dropdown-menu" aria-labelledby="postMenuButton">
              <a class="dropdown-item" id="btn-edit"  data-toggle="modal" data-target="#myModal">수정</a>

              <a class="dropdown-item delete-post" href="{% url 'Posts:delete_post' pk=post.id %}" data-post-id="{{ post.pk }}">삭제</a>
            </div>
            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="myModalLabel">비밀번호 입력</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <form id="password-form" action = "{% url 'Posts:post_update' pk=post.id %}">
                      {% csrf_token %}
                      <div class="form-group row">
                        <label for="password-input" class="col-sm-3 col-form-label">비밀번호</label>
                        <div class="col-sm-9">
                          <input type="password" name="password" class="form-control" id="password-input" required>
                        </div>
                      </div>
                    </form>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">닫기</button>
                    <button type="button" class="btn btn-primary" id="password-confirm">확인</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
<!-- 이미지를 클릭했을 때 확대되는 모달 -->

    <p class="lead" style="margin-top: 20px;">{{ post.content|safe }}</p>
    </div>
  </div>
  
  <div class="row my-5">
    <div class="col-md-12">
      <hr class="my-4">

      <h4 class="mb-4">{{ comment_count }} 개의 댓글</h4>
      {% for comment in comment_list %}
      <div class="card comment-card"id = 'comment-{{comment.id}}'>
        {% if comment.is_deleted %}
        <div class="card-body">
          <p style="color: red;">삭제된 댓글입니다.</p>
        </div>
        {% else %}
        <div class="card-body" >
          <div>
            <span class="emoji" style="font-size: 15px;">👤</span> 
            <span class="card-title">{{ comment.author }}
              <small class="text-muted"> ({{ comment.author_ip }})
              </small>
            </span>
            <div class="dropdown float-right">
              <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="#">수정</a>
                
                <a class="dropdown-item" onclick="showDeleteConfirmation({{comment.id}})">삭제</a>
                
              </div>
              <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="myModalLabel">비밀번호 입력</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      <form id="password-form">
                        {% csrf_token %}
                        <div class="form-group row">
                          <label for="password-input" class="col-sm-3 col-form-label">비밀번호</label>
                          <div class="col-sm-9">
                            <input type="password" name="password" class="form-control" id="password-input" required>
                          </div>
                        </div>
                      </form>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">닫기</button>
                      <button type="button" class="btn btn-primary" id="password-confirm">확인</button>
                    </div>
                  </div>
                </div>
              </div>
              
            </div>
          </div>
          <br>

    {% for img_tag in img_tags %}
        <a href="{{ img_tag }}" data-lightbox="post-images">
            <img class="post-image" src="{{ img_tag }}" alt="post-image">
        </a>
    {% endfor %}

          <p class="card-text">{{ comment.content|safe }}</p>

        </div>
        <div class="card-footer">
          <small>{{ comment.time }}</small>
        </div>
        {% endif %}
      </div>
    
      {% empty %}
      <p>댓글이 없습니다.</p>
      {% endfor %}
    </div>
  </div>

<!-- 댓글 작성 폼 -->
<div id="comment-form-wrapper" style="background-color: #f5c2c2; padding: 20px; border-radius:15px;">

  <form id="comment-form" method="post">
    {% csrf_token %}
    <div class="form-group row">
      <label for="{{ form.author.id_for_label }}" class="emoji" style="font-size: 20px; margin-left:15px">👤</label>
      <div class="col-sm-3">
        
        <input type="text" required=True class="form-control" id="{{ form.author.id_for_label }}" name="{{ form.author.name }}" maxlength="{{ form.author.field.max_length }}" required, placeholder="닉네임">
      
      </div>
      <label for="{{ form.password.id_for_label }}" class="emoji" style="font-size: 20px;">🔒</label>
      <div class="col-sm-3">
    
        <input type="password" required=True name="{{ form.password.name }}" id="{{ form.password.id_for_label }}" class="form-control" placeholder="비밀번호 입력">
      </div>
    </div>
    <div class="form-group column">
      <textarea name="content" placeholder="내용" class="form-control" style="height: 100px;", required=True></textarea>
      <div style=" margin-top:10px"><button type="submit" class="btn btn-primary" style="  display: block;
        margin-left: auto;
        margin-right: 0;">작성</button></div>

      
    </div>

  </form>
</div>


{% endblock %}

{% block script %}<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>
  function enlargeImage(imgElement) {
    var imageUrl = imgElement.src;
    window.open(imageUrl, '_blank');
}
tinymce.init({
    selector: "textarea",
    theme: "modern",
    height: 500,
    paste_data_images: true,
    plugins: [
        "advlist autolink lists link image charmap print preview hr anchor pagebreak",
        "searchreplace wordcount visualblocks visualchars code fullscreen",
        "insertdatetime media nonbreaking save table contextmenu directionality",
        "emoticons template paste textcolor colorpicker textpattern"
    ],
    toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
    toolbar2: "print preview media | forecolor backcolor emoticons",
    image_advtab: true,
    file_picker_callback: function (callback, value, meta) {
        if (meta.filetype == 'image') {
            $('#upload').trigger('click');
            $('#upload').on('change', function () {
                var file = this.files[0];
                var reader = new FileReader();
                reader.onload = function (e) {
                    callback(e.target.result, {
                        alt: ''
                    });
                };
                reader.readAsDataURL(file);
            });
        }
    },
    templates: [{
        title: 'Test template 1',
        content: 'Test 1'
    }, {
        title: 'Test template 2',
        content: 'Test 2'
    }]
});

</script>
<script>
  function showDeleteConfirmation(commentId) {
    const password = prompt("비밀번호를 입력하세요:", "");
    var data = new FormData();
    data.append('password', password);
    if (password != null) {
      const url = "/posts/" + "comment/" + commentId + "/delete/";
      const csrf_token = document.getElementsByName("csrfmiddlewaretoken")[0].value;
      const xhr = new XMLHttpRequest();
      xhr.open("POST", url, true);
      xhr.setRequestHeader("X-CSRFToken", csrf_token);
      xhr.onload = function () {
        if (xhr.status === 200) {
          const commentElement = document.getElementById("comment-" + commentId);
          commentElement.parentNode.removeChild(commentElement);
          alert("댓글이 삭제됐습니다.")
        } else {
          alert("비밀번호가 틀렸습니다.");
        }
      };
      xhr.send(data);
    }
  }

  
</script>
<script>
  $("#password-confirm").on("click", function(e) {
    e.preventDefault();

    var password = $("#password-input").val();
    var post_password = "{{ post.password }}";
    if (password === post_password) {
      window.location.href = "/posts/" + "post/" + {{post.id}} + "/update/";
    } else {
      alert('비밀번호가 일치하지 않습니다.');
      $("#password-input").val('');
    }
  });
</script>


  
{% endblock %}

Posts/templates/Posts/list_post.html
{% extends 'base.html' %}
{% block style %}
<style>
  .posts-header {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    margin-bottom: 20px;
    margin-top: 20px;
  }

  .posts-header h1 {
    margin: 0;
  }

  .post-item {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 20px;
    border: 1px solid #ccc;
    margin-bottom: 20px;
  }

  .post-item h2 {
    margin: 0;
    font-size: 24px;
  }

  .post-item .date {
    font-size: 16px;
  }  
  /* 각 게시물을 담고 있는 요소인 .card-body에 대한 스타일 */
  .card-body {
    display: flex;
    flex-direction: column;
    justify-content: space-between;
    height: 100%;
  }

  /* 날짜를 담고 있는 .text-muted 클래스에 대한 스타일 */
  .text-muted {
    margin-left: auto;  /* 왼쪽 여백을 auto로 지정하여 오른쪽으로 붙입니다. */
  }

  /* 게시물 제목을 담고 있는 h5 태그에 대한 스타일 */
  h5.card-title {
    margin-top: 0;  /* 제목 상단 여백 제거 */
    margin-bottom: 10px;  /* 제목 하단 여백 추가 */
  }
</style>
{% endblock %}

{% block content %}
<div class="container">
  <div class="posts-header">
    <h3 style="font-family: 'NanumGothic'">자유게시판</h1>
    <div>
      <a href="{% url 'Posts:post_new' %}" class="btn">✏️</a>
    </div>
  </div>
  <hr>
</div>

  {% if posts %}

  <div class="row">
    {% for post in posts %}
    {% if post.is_deleted %}
    {% else %}
    <div class="col-md-12">
      <div class="card mb-4 shadow-sm">
        <div class="card-body">
          <div class="d-flex justify-content-between align-items-center">
            <h5 class="card-title">{{ post.title }}</h5>
            <small class="text-muted"><span class="emoji" style="font-size: 15px;">🕒</span>{{ post.time}}</small>
          </div>
          <small class="text-muted"><span class="emoji" style="font-size: 15px;">👤</span> {{ post.author }}</small>

        </div>
        <a href="{% url 'Posts:post_detail' post.id %}" class="stretched-link"></a>
      </div>
    </div>
    {% endif %}
    {% endfor %}
    </ul>
      <nav aria-label="Page navigation example", class = "text-center">
        <ul class="pagination justify-content-center text-center">
          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link btn-rounded" href="?page=1" aria-label="First">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">First</span>
            </a>
          </li>
          <li class="page-item">
            <a class="page-link btn-rounded" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&lt;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}
      
          {% for num in page_obj.paginator.page_range %}
          {% if page_obj.number == num %}
          <li class="page-item active">
            <a class="page-link btn-rounded" href="#">{{ num }}</a>
          </li>
          {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <li class="page-item">
            <a class="page-link btn-rounded" href="?page={{ num }}">{{ num }}</a>
          </li>
          {% endif %}
          {% endfor %}
      
          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link btn-rounded" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&gt;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          <li class="page-item">
            <a class="page-link btn-rounded" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Last</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
    {% else %}
      
      <p>No posts are available.</p>
    {% endif %}
  </div>

{% endblock %}

Posts/templates/Posts/post_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <div class="container mt-5">
    <div class="row">
      <div class="col-md-8 offset-md-2">
        <h2 class="mb-4">게시물 삭제</h2>
        <p>정말로 이 게시물을 삭제하시겠습니까?</p>
        <form method="post" id="deleteForm">
          {% csrf_token %}
          <div class="form-group">
            <label for="password">게시물 비밀번호</label>
            <input type="password" class="form-control" id="password" name="password">
          </div>
          <button type="button" class="btn btn-danger" onclick="checkPassword()"><i class="bi bi-trash"></i> 삭제</button>
          <a href="{{ post.get_absolute_url }}" class="btn btn-secondary"><i class="bi bi-arrow-left"></i> 취소</a>
        </form>
      </div>
    </div>
  </div>

  <script>
    function checkPassword() {
      var password = document.getElementById("password").value;

      // Ajax를 사용하여 서버에 비밀번호 확인 요청
      // 여기서는 비동기적인 요청을 모의로 구현한 것이므로 실제 서버에 맞게 수정해야 합니다.
      // 예: 비밀번호가 일치하면 삭제 처리, 불일치하면 에러 메시지 반환

      // 비밀번호가 일치하지 않는 경우
      // 여기서는 예시로 간단한 alert을 사용했지만, 실제 프로젝트에서는 더 나은 방식으로 사용자에게 알림을 표시해야 합니다.
      if (password !== "{{ post.password }}") {
        alert("비밀번호가 틀렸습니다.");
      } else {
        // 비밀번호가 일치하는 경우 폼 제출
        document.getElementById("deleteForm").submit();
      }
    }
  </script>
{% endblock %}